# .goreleaser.yml
builds:
  - id: caddy
    main: "./cmd/caddy/main.go"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
      - "6"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    env:
      - "CGO_ENABLED=0"
