# .goreleaser.yml
builds:
  - id: caddy
    main: "./cmd/standard/main.go"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    env:
      - "CGO_ENABLED=0"
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
  - id: caddy-mini
    main: "./cmd/minimal/main.go"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    env:
      - "CGO_ENABLED=0"
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
