version: "3"

tasks:
  generate:
    desc: Generate source code
    deps:
      - generate:otelcol

  generate:otelcol:
    desc: Generate opentelemetry-collector source code
    cmds:
      - ocb --skip-compilation --config=manifest.yml
    dir: modules/otelcol/components

  docs:
    desc: Serve docs locally
    cmds:
      - pkgsite

  caddy:
    desc: Run caddy command after building it
    deps:
      - build
    cmds:
      - ./caddy {{.CLI_ARGS}}

  start:
    desc: Start local caddy server after building it
    deps:
      - build
    cmds:
      - ./caddy run {{.CLI_ARGS}}

  build:
    desc: Build caddy server with all modules
    deps:
      - build:linux
      - build:windows

  build:darwin:
    desc: Build for darwin
    cmds:
      - go build -o caddy ./cmd/standard
    env:
      GOOS: darwin
      GOARCH: amd64

  build:linux:
    desc: Build for linux
    cmds:
      - go build -o caddy ./cmd/standard
      - sudo setcap cap_net_bind_service=+ep ./caddy
    env:
      CGO_ENABLED: 0

  build:windows:
    desc: Build for windows
    cmds:
      - go build -o caddy.exe ./cmd/standard
    env:
      GOOS: windows
      GOARCH: amd64

  release:build:
    desc: Build cross-platform caddy server with all modules
    cmds:
      - goreleaser build --clean

  release:
    desc: CI Release - Do not run locally
    cmds:
      - goreleaser

  tidy:
    desc: Tidy up go.mod dependencies
    cmds:
      - go mod tidy

  # tests
  test:
    desc: Run tests
    cmds:
      - go test -v ./...
